
SELECT * FROM "Customer" ;
--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue From "Customer" group by gender 
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,SUM(purchase_amount) as rev_spent from "Customer" WHERE discount_applied='Yes'
group by customer_id HAVING SUM(purchase_amount)> (SELECT avg(purchase_amount) FROM "Customer") 
order by customer_id asc; 

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,avg(review_rating) as rate FROM "Customer" group by item_purchased 
order by rate  DESC limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type , ROUND(AVG(purchase_amount)) as avg_purch_amount FROM "Customer" 
WHERE shipping_type in ('Express','Standard') group by shipping_type order by avg_purch_amount desc;
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,Count(customer_id) as no_of_customer,Round(AVG(purchase_amount)) as avg_spen, SUM(purchase_amount) as total_rev 
FROM "Customer" 
WHERE subscription_status in ('Yes', 'No') group by  subscription_status order by avg_spen,total_rev desc;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT   item_purchased ,ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate 
FROM "Customer"
group by item_purchased order by discount_rate desc limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type as (
select customer_id,previous_purchases,
           CASE 
		      WHEN previous_purchases=1 THEN 'NEW' 
              WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
			  ELSE 'LOYAL'
		   END AS SEGMENT 
FROM "Customer")
SELECT SEGMENT, COUNT(*) as "No_of_customer"
FROM customer_type 
group by SEGMENT;

--Q8. What are the top 3 most purchased products within each category? 
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS rn
    FROM "Customer"
    GROUP BY category, item_purchased
)
SELECT rn, category, item_purchased, purchase_count
FROM product_counts
WHERE rn <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,COUNT(customer_id) AS REPEAT_BUYERS from "Customer" where previous_purchases>5 
group by subscription_status;
--Q10. What is the revenue contribution of each age group? 
select age_group , SUM(purchase_amount) AS TOTAL_REV from "Customer" GROUP BY age_group;